In [1]:
! pip install tensorflow numpy nltk



[notice] A new release of pip is available: 23.2.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
! pip install fastapi uvicorn openai



[notice] A new release of pip is available: 23.2.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [16]:
from fastapi import FastAPI, HTTPException
import openai
import os
from pydantic import BaseModel

# Setup your OpenAI API key
openai.api_key = "AIzaSyDWqu5kkx8THPepAtTLNG5R1CApcgqWltE"

app = FastAPI()

# Define a Request Model
class ChatRequest(BaseModel):
    message: str

# Define the chatbot interaction endpoint
@app.post("/chat/")
async def chat(request: ChatRequest):
    user_message = request.message

    try:
        # Request to OpenAI API (GPT-3/4)
        response = openai.Completion.create(
            model="Gemini 1.5",  # You can use different models like "gpt-3.5-turbo"
            prompt=user_message,
            max_tokens=150
        )
        bot_message = response.choices[0].text.strip()
        return {"response": bot_message}
    except Exception as e:
        raise HTTPException(status_code=500, detail="Error interacting with the model: " + str(e))

# Run the application with Uvicorn
# uvicorn main:app --reload


In [17]:
! Uvicorn running on http://127.0.0.1:8000 


Usage: uvicorn [OPTIONS] APP
Try 'uvicorn --help' for help.

Error: Got unexpected extra arguments (on http://127.0.0.1:8000)


In [18]:
import numpy as np
import random

# Define states and actions
# States could be represented by different types of user inputs (e.g., "greet", "ask_name", "thank")
states = ["greet", "ask_name", "thank"]
actions = ["hello", "what's your name?", "you're welcome"]
n_states = len(states)
n_actions = len(actions)

# Initialize Q-table
Q = np.zeros((n_states, n_actions))

# Define rewards for specific action-state pairs
# For simplicity, the rewards are just randomly assigned here
rewards = {
    ("greet", "hello"): 1, 
    ("ask_name", "what's your name?"): 1,
    ("thank", "you're welcome"): 1,
}

# Parameters for Q-learning
alpha = 0.1  # Learning rate
gamma = 0.9  # Discount factor
epsilon = 0.2  # Exploration factor

# Mapping of states to their indices
state_index = {state: idx for idx, state in enumerate(states)}

def choose_action(state_idx):
    """Choose action using epsilon-greedy strategy"""
    if random.uniform(0, 1) < epsilon:
        # Exploration: Choose a random action
        return random.randint(0, n_actions - 1)
    else:
        # Exploitation: Choose the best action from the Q-table
        return np.argmax(Q[state_idx])

def chatbot():
    """Simulate chatbot interactions and Q-learning"""
    for episode in range(1000):  # Number of training episodes
        # Randomly choose a state (user input)
        state = random.choice(states)
        state_idx = state_index[state]
        
        # Choose action (response) based on the current state
        action_idx = choose_action(state_idx)
        action = actions[action_idx]
        
        # User feedback (reward) after the chatbot's response
        if (state, action) in rewards:
            reward = rewards[(state, action)]
        else:
            reward = -1  # Penalty for inappropriate response

        # Q-learning update
        next_state = random.choice(states)  # Simulating next state (randomly)
        next_state_idx = state_index[next_state]
        
        Q[state_idx, action_idx] = Q[state_idx, action_idx] + alpha * (
            reward + gamma * np.max(Q[next_state_idx]) - Q[state_idx, action_idx]
        )
        
        # Print the Q-table for visualization
        if episode % 100 == 0:
            print(f"Episode {episode}")
            print(Q)
        
    # After training, test the chatbot
    test_conversation()

def test_conversation():
    """Test the trained chatbot"""
    print("\nTesting the trained chatbot...\n")
    
    # Test interactions
    for state in states:
        state_idx = state_index[state]
        action_idx = np.argmax(Q[state_idx])
        action = actions[action_idx]
        
        print(f"User input: {state} -> Chatbot response: {action}")

# Start chatbot training
chatbot()


Episode 0
[[ 0.   0.   0. ]
 [ 0.   0.   0. ]
 [-0.1  0.   0. ]]
Episode 100
[[ 2.28815471  0.15505764 -0.10522331]
 [ 0.03055533  2.18760072 -0.06363927]
 [ 0.10877692  0.01185685  2.54138652]]
Episode 200
[[ 4.48097916  0.49221333  0.05138778]
 [ 0.39867933  3.90016789 -0.06363927]
 [ 0.37171712  0.47560414  4.33802947]]
Episode 300
[[5.75119897 1.47600954 0.05138778]
 [1.17884689 5.54664404 0.84543125]
 [1.30308129 0.82411517 5.85098664]]
Episode 400
[[6.74346443 2.32934314 1.25697638]
 [1.17884689 6.83105679 1.58475185]
 [2.44594895 1.21860757 6.80741134]]
Episode 500
[[7.52779818 2.9235222  2.07497323]
 [2.59028731 7.58338263 1.96532148]
 [3.26496119 2.06282963 7.65086261]]
Episode 600
[[8.16669763 3.76367657 3.42764317]
 [2.9645885  8.19422669 2.39873518]
 [3.55728434 2.83561466 8.27668216]]
Episode 700
[[8.59859232 4.04817272 4.2727595 ]
 [3.30842275 8.67459831 2.39873518]
 [4.40308251 4.09889814 8.70252855]]
Episode 800
[[9.00190894 4.83616269 5.00792346]
 [4.27728685 8.9805649